import { Course } from '@/types';

export const ACADEMIC_TRANSCRIPT: Course[] = [
  {
    courseCode: 'QP012',
    courseTitle: 'National Defense Education 3',
    courseTitleInVietnamese: 'Giáo dục quốc phòng và an ninh 3',
    group: 'D01',
    numberOfCredit: 2,
    tenGradeSystem: 10,
    letterGradeSystem: 'A',
    accumulation: false,
    categories: 'Military',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'QP013',
    courseTitle: 'National Defense Education 4',
    courseTitleInVietnamese: 'Giáo dục quốc phòng và an ninh 4',
    group: 'D01',
    numberOfCredit: 2,
    tenGradeSystem: 10,
    letterGradeSystem: 'A',
    accumulation: false,
    categories: 'Military',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'CT100',
    courseTitle: 'College Study Skills',
    courseTitleInVietnamese: 'Kỹ năng học đại học',
    group: 'D02',
    numberOfCredit: 2,
    tenGradeSystem: 9.6,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Basic',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'CT200',
    courseTitle: 'Fundamentals of Information Technology',
    courseTitleInVietnamese: 'Nền tảng công nghệ thông tin',
    group: 'D02',
    numberOfCredit: 4,
    tenGradeSystem: 8.2,
    letterGradeSystem: 'B+',
    accumulation: true,
    categories: 'Basic',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'QP010',
    courseTitle: 'National Defense Education 1',
    courseTitleInVietnamese: 'Giáo dục quốc phòng và an ninh 1',
    group: 'D04',
    numberOfCredit: 2,
    tenGradeSystem: 8.9,
    letterGradeSystem: 'B+',
    accumulation: false,
    categories: 'Military',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'QP011',
    courseTitle: 'National Defense Education 2',
    courseTitleInVietnamese: 'Giáo dục quốc phòng và an ninh 2',
    group: 'D04',
    numberOfCredit: 2,
    tenGradeSystem: 9.5,
    letterGradeSystem: 'A',
    accumulation: false,
    categories: 'Military',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'CC009',
    courseTitle: 'TOEIC 670',
    courseTitleInVietnamese: 'TOEIC 670',
    group: 'x',
    numberOfCredit: 10,
    tenGradeSystem: 'EX',
    letterGradeSystem: 'M',
    accumulation: false,
    categories: 'Languages',
    semester: 'Semester 1 Academic Year 2021-2022',
  },
  {
    courseCode: 'CT109',
    courseTitle: 'Programming Basic A',
    courseTitleInVietnamese: 'Lập trình căn bản A',
    group: '10',
    numberOfCredit: 4,
    tenGradeSystem: 9.2,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Programming',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'CT172',
    courseTitle: 'Discrete Mathematics',
    courseTitleInVietnamese: 'Toán rời rạc',
    group: '07',
    numberOfCredit: 4,
    tenGradeSystem: 9.5,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Math',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'ML014',
    courseTitle: 'Marxist-Leninist Philosophy',
    courseTitleInVietnamese: 'Triết học Mác-Lênin',
    group: '23',
    numberOfCredit: 3,
    tenGradeSystem: 7.4,
    letterGradeSystem: 'B',
    accumulation: true,
    categories: 'Politics',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'TC001',
    courseTitle: 'Athletics 1',
    courseTitleInVietnamese: 'Điền kinh 1',
    group: '11',
    numberOfCredit: 1,
    tenGradeSystem: 9.0,
    letterGradeSystem: 'A',
    accumulation: false,
    categories: 'Athletics',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'TN001',
    courseTitle: 'Calculus A1',
    courseTitleInVietnamese: 'Vi tích phân A1',
    group: '01',
    numberOfCredit: 3,
    tenGradeSystem: 9.8,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Math',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'TN012',
    courseTitle: 'Linear Algebra and Analytic Geometry',
    courseTitleInVietnamese: 'Đại số tuyến tính và hình học',
    group: '10',
    numberOfCredit: 4,
    tenGradeSystem: 10.0,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Math',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'XH014',
    courseTitle: 'General Documents & Archives',
    courseTitleInVietnamese: 'Văn bản và lưu trữ học đại cương',
    group: '03',
    numberOfCredit: 2,
    tenGradeSystem: 8.5,
    letterGradeSystem: 'B+',
    accumulation: true,
    categories: 'Documents',
    semester: 'Semester 2 Academic Year 2021-2022',
  },
  {
    courseCode: 'KL001',
    courseTitle: 'General Law',
    courseTitleInVietnamese: 'Pháp luật đại cương',
    group: '08',
    numberOfCredit: 2,
    tenGradeSystem: 9.3,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Law',
    semester: 'Semester 3 Academic Year 2021-2022',
  },
  {
    courseCode: 'ML016',
    courseTitle: 'Marxist-Leninist Political Economics',
    courseTitleInVietnamese: 'Kinh tế chính trị Mác-Lênin',
    group: '08',
    numberOfCredit: 2,
    tenGradeSystem: 8.5,
    letterGradeSystem: 'B+',
    accumulation: true,
    categories: 'Politics',
    semester: 'Semester 3 Academic Year 2021-2022',
  },
  {
    courseCode: 'TN010',
    courseTitle: 'Probability and Statistics',
    courseTitleInVietnamese: 'Xác xuất thống kê',
    group: '02',
    numberOfCredit: 3,
    tenGradeSystem: 10.0,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Math',
    semester: 'Semester 3 Academic Year 2021-2022',
  },
  {
    courseCode: 'CT173',
    courseTitle: 'Computer Architecture',
    courseTitleInVietnamese: 'Kiến trúc máy tính',
    group: '04',
    numberOfCredit: 3,
    tenGradeSystem: 9.0,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Basic',
    semester: 'Semester 1 Academic Year 2022-2023',
  },
  {
    courseCode: 'CT176',
    courseTitle: 'Object Oriented Programming',
    courseTitleInVietnamese: 'Lập trình hướng đối tượng',
    group: '07',
    numberOfCredit: 3,
    tenGradeSystem: 9.3,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Basic',
    semester: 'Semester 1 Academic Year 2022-2023',
  },
  {
    courseCode: 'CT177',
    courseTitle: 'Data Structures',
    courseTitleInVietnamese: 'Cấu trúc dữ liệu',
    group: '09',
    numberOfCredit: 3,
    tenGradeSystem: 10.0,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Basic',
    semester: 'Semester 1 Academic Year 2022-2023',
  },
  {
    courseCode: 'CT179',
    courseTitle: 'IT System Administration',
    courseTitleInVietnamese: 'Quản trị hệ thống',
    group: '06',
    numberOfCredit: 3,
    tenGradeSystem: 9.1,
    letterGradeSystem: 'A',
    accumulation: true,
    categories: 'Specialized',
    semester: 'Semester 1 Academic Year 2022-2023',
  },
];

export const PROJECTS = [
  {
    thumbnail: '1.jpeg',
    title: 'ARTSHOP - ARTELEVATE - MICROSERVICES 12 - 2023',
    description:
      'Art Elevate is a .NET application demonstrating a real-time art auction platform. Utilizing a microservices architecture, it integrates Next.js 14 and dotnet 8 for frontend and backend, respectively. Using SignalR – Websocket for real-time communication, RabbitMQ as a message broker, and gRPC for enhanced performance. Authentication is managed through JWT Token using NextAuth and Duende Identity Server and with AI assistant. Deployment is streamlined using Docker/Kubernetes and Xunit for testing.',
  },
  {
    thumbnail: '2.jpeg',
    title: 'ESHOP CLONE-SERVICE-BASE ARCHITECTURE 01 - 2024',
    description:
      'eShop Clone is a clone of the open-source eShop project developed by Microsoft (https://github.com/dotnet/eshop). It provides a complete e-commerce platform, including a web user interface, RESTful APIs, and back-end services using serivces-based architecture. eShop Clone is built with dotnet 8, including pgvecore, embedding model and more.',
  },
  {
    thumbnail: '3.jpeg',
    title: 'REAL-TIME CHAT APPLICATION - WEBSITE 02 - 2024',
    description:
      'This project utilizes dotnet 8 for the backend and Next.js 14 for the frontend, incorporating SignalR for real-time communication technology.',
  },
  {
    thumbnail: '4.jpeg',
    title: 'E-COMMERCE – DASHBOARD & CMS - WEBSITE 07 - 2023',
    description:
      'Using Next.js 13 App Router to build a fully functional E-Commerce with Admin Dashboard with seamless navigation and user experience.',
  },
  {
    thumbnail: '5.png',
    title: 'SPOTIFY CLONE - WEBSITE 08 - 2023',
    description:
      'Build a Full Stack Spotify Clone with Next.js 13.4, React, Tailwind, Supabase,PostgreSQL, and Stripe.',
  },
  {
    thumbnail: '6.jpeg',
    title: 'AIRBNB CLONE-WEBSITE 08 - 2023',
    description:
      'Build a full-stack Airbnb clone, Put a special emphasis on the Next.js 13 App Router.',
  },
  {
    thumbnail: '7.webp',
    title: 'DISCORD CLONE - WEBSITE 09 - 2023',
    description:
      'This project is to create an end-to-end fullstack and real-time discord clone, all with servers, channels, video calls, audio calls, editing and deleting messages as well as member roles using Next.js 13.',
  },
  {
    thumbnail: '8.jpg',
    title: 'LMSPLATFORM - WEBSITE 09 - 2023',
    description:
      'Build LMS (Learning Management System) platform. Using the latest tech such as Next.js 13 with the App Router, Prisma as an ORM, Stripe for payments.',
  },

  {
    thumbnail: '9.jpeg',
    title: 'DIGITAL MARKETPLACE - WEBSITE 12 - 2023',
    description:
      'This project uses Nextjs 13 and Express to create a e-commerce websites with CMS management.',
  },
];
